name: Playwright Tests CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Debug Allure Results
      - name: Debug Allure Results
        if: always()
        run: |
          echo "===== allure-results folder ====="
          ls -R allure-results || echo "allure-results NOT FOUND"

      # Upload Playwright HTML Report
      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7

      # Setup Java for Allure
      - name: Setup Java
        if: always()
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Install Allure CLI
      - name: Install Allure CLI
        if: always()
        run: npm install -g allure-commandline

      # Validate Allure Results
      - name: Validate Allure Results
        if: always()
        run: |
          if [ ! -d "allure-results" ] || [ -z "$(ls -A allure-results 2>/dev/null)" ]; then
            echo "allure-results is missing or empty"
            exit 0
          else
            echo "allure-results found"
          fi

      # Generate Allure Report
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report

      # Debug Allure Report
      - name: Check Allure Report Output
        if: always()
        run: |
          ls -R allure-report || echo "allure-report NOT FOUND"

      # Upload Allure Report
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          if-no-files-found: ignore
          retention-days: 7

      # Upload test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore
          retention-days: 7